import Head from 'next/head'
import HomePage from '../components/Home'
import { Divider, Box, Text } from '@chakra-ui/react'

export default function Home() {
  return (
    <div>
      <Head>
        <title>GitHub - API</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <HomePage />
      <Divider marginTop={10} orientation='horizontal' borderColor={'#58a6ff'} />
      <Box margin={6}>
        <Text textAlign={'center'} fontSize='1xl'>Developed by: <a href="https://www.linkedin.com/in/raphael-caetano-39aa8519a/" target={'_blank'}>Raphael Caetano</a></Text>
      </Box>
    </div>
  )
}
